feat: Added the favourite tweet of tomdieu
gdscuy1/tweets pull request #2
Opened 2023-10-15 21:57 UTC by Tomdieu

2023-10-15 22:19 UTC, Edmond22-prog reviewed
Il faut un tweet du GDSC UY1

2023-10-15 22:23 UTC, Edmond22-prog commented
Et pas de screenshoot fait.

2023-10-15 23:38 UTC, Tomdieu commented
d'accord

2023-10-16 05:02 UTC, Joel-Fah requested changes
1. Tu dois ajouter un tweet du [GDSC UY1](https://x.com/dsc_uy1)
2. Faire la capture d'écran du même tweet

2023-10-17 18:22 UTC, Tomdieu commented
j'ai deja fait

2023-10-17 18:32 UTC, Joel-Fah requested changes

2023-10-17 18:32 UTC, Joel-Fah commented on archives/2023/pictures/Screenshot from 2023-10-17 19-16-19.png
Le nom de l'image ci doit être sous le format:
**\<github-username\>.png**

2023-10-17 18:36 UTC, Tomdieu commented on archives/2023/pictures/Screenshot from 2023-10-17 19-16-19.png
j'ai update

2023-10-17 20:11 UTC, Joel-Fah approved these changes

2023-10-17 20:12 UTC, merged